const data = {
  total: 15,
  offset: 0,
  rows: 15,
  users: [
    {
      id: "1",
      name: "Ronaldo Abreu",
      email: "ronaldo.abreu@meusite.com.br",
      phone: "(14) 99745-1234",
      amount: "251.59",
      photo_url: "https://desafio.eadplataforma.com/front/assets/ronaldo.jpg",
      status: "1",
    },
    {
      id: "2",
      name: "Geovane Felix",
      email: "geovane.felix@meusite.com.br",
      phone: "(14) 99745-5678",
      amount: "265.59",
      photo_url: "https://desafio.eadplataforma.com/front/assets/geovane.jpg",
      status: "0",
    },
    {
      id: "3",
      name: "Eloisa Santos",
      email: "eloisa.santos@meusite.com.br",
      phone: "(14) 99745-9123",
      amount: "753.03",
      photo_url: "https://desafio.eadplataforma.com/front/assets/eloisa.jpg",
      status: "1",
    },
    {
      id: "4",
      name: "Silvia Martins",
      email: "silvia.martins@meusite.com.br",
      phone: "(14) 99745-5467",
      amount: "430.13",
      photo_url: "https://desafio.eadplataforma.com/front/assets/silvia.jpg",
      status: "0",
    },
    {
      id: "5",
      name: "Felipe Garcia",
      email: "felipe.garcia@meusite.com.br",
      phone: "(14) 99745-8971",
      amount: "710.39",
      photo_url: "https://desafio.eadplataforma.com/front/assets/felipe.jpg",
      status: "1",
    },
    {
      id: "6",
      name: "Juliana Ferreira",
      email: "juliana.ferreira@meusite.com.br",
      phone: "(14) 99745-2345",
      amount: "660.79",
      photo_url: "https://desafio.eadplataforma.com/front/assets/juliana.jpg",
      status: "0",
    },
    {
      id: "7",
      name: "Robson Silva",
      email: "robson.silva@meusite.com.br",
      phone: "(14) 99745-5647",
      amount: "188.23",
      photo_url: "https://desafio.eadplataforma.com/front/assets/robson.jpg",
      status: "0",
    },
    {
      id: "8",
      name: "Rafaela Sanches",
      email: "rafaela.sanches@meusite.com.br",
      phone: "(14) 98725-8373",
      amount: "457.69",
      photo_url: "https://desafio.eadplataforma.com/front/assets/rafaela.jpg",
      status: "1",
    },
    {
      id: "9",
      name: "Maria Aparecida",
      email: "maria.aparecida@meusite.com.br",
      phone: "(14) 99622-3329",
      amount: "145.06",
      photo_url: "https://desafio.eadplataforma.com/front/assets/maria.jpg",
      status: "0",
    },
    {
      id: "10",
      name: "Paulo Nunes",
      email: "paulo.nunes@meusite.com.br",
      phone: "(14) 98717-2313",
      amount: "197.49",
      photo_url: "https://desafio.eadplataforma.com/front/assets/paulo.jpg",
      status: "1",
    },
    {
      id: "11",
      name: "Janice Fatima",
      email: "janice.fatima@meusite.com.br",
      phone: "(14) 99312-1429",
      amount: "545.06",
      photo_url: "https://desafio.eadplataforma.com/front/assets/janice.jpg",
      status: "0",
    },
    {
      id: "12",
      name: "Alessandra Silva",
      email: "alessandra.silva@meusite.com.br",
      phone: "(14) 98633-0849",
      amount: "879.81",
      photo_url:
        "https://desafio.eadplataforma.com/front/assets/alessandra.jpg",
      status: "0",
    },
    {
      id: "13",
      name: "Julia dos Anjos",
      email: "julia.anjos@meusite.com.br",
      phone: "(14) 99654-0867",
      amount: "578.92",
      photo_url: "https://desafio.eadplataforma.com/front/assets/julia.jpg",
      status: "1",
    },
    {
      id: "14",
      name: "Andre Araujo",
      email: "andre.araujo@meusite.com.br",
      phone: "(14) 99647-0125",
      amount: "349.45",
      photo_url: "https://desafio.eadplataforma.com/front/assets/andre.jpg",
      status: "0",
    },
    {
      id: "15",
      name: "Fatima dos Santos",
      email: "fatima.santos@meusite.com.br",
      phone: "(14) 99698-0478",
      amount: "698.14",
      photo_url: "https://desafio.eadplataforma.com/front/assets/fatima.jpg",
      status: "0",
    },
  ],
};

export default data;
